import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

// ReactiveSearch
import { ReactiveBase } from "@appbaseio/reactivesearch";

const inter = Inter({ subsets: ["latin"] });
const es_url = process.env.ES_URL || "http://localhost:9200";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <ReactiveBase
          // Get URL from env var ES_URL or default to localhost:9200
          url={es_url}
          app="business"
          credentials="elasticsearch:changeme"
        />
        <h1 className="text-3xl font-bold">Hello World</h1>
      </main>
    </>
  );
}
