import Head from "next/head";

import styles from "@/styles/Home.module.css";

// SearchKit
import React from "react";
import Client from "@searchkit/instantsearch-client";
import {
  InstantSearch,
  SearchBox,
  Hits,
  Highlight,
  RefinementList,
  Pagination,
  NumericMenu,
} from "react-instantsearch-dom";

const searchClient = Client({
  url: "/api/search",
});

function Hit(props: { hit: any }) {
  const { hit } = props;
  return (
    <div>
      <div>
        <Highlight attribute="title" hit={hit} />
        <Highlight attribute="description" hit={hit} />
      </div>
    </div>
  );
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <InstantSearch indexName="business" searchClient={searchClient}>
          <SearchBox />
          <Hits hitComponent={Hit} />
        </InstantSearch>
        <h1 className="text-3xl font-bold">Hello World</h1>
      </main>
    </>
  );
}
